fix(gnovm): correct filetest directive behavior (#3697)
The test result is misleading. Without an output directive set, the
current logic does not provide a prompt even when actual output occurs.

```go
package main

func main() {
	println("ok")
}

// Error:
// panic xxx
```

## before fix:

=== RUN   TestFiles
=== PAUSE TestFiles
=== CONT  TestFiles
=== RUN   TestFiles/a111.gno
--- PASS: TestFiles (0.14s)
    --- PASS: TestFiles/a111.gno (0.01s)
PASS
ok  	command-line-arguments	1.619s


## after fix:

=== RUN   TestFiles
=== PAUSE TestFiles
=== CONT  TestFiles
=== RUN   TestFiles/a111.gno
    files_test.go:92: unexpected output:
        ok

--- FAIL: TestFiles (0.13s)
    --- FAIL: TestFiles/a111.gno (0.01s)
FAIL
FAIL	command-line-arguments	1.479s
FAIL

---------

Co-authored-by: Morgan <morgan@morganbaz.com>