fix(lint): fix 'make install' failure due to bad 'BeginTransaction' c… (#3369)
Addresses #3368 

…all in lint.io

lint.go: add missing 'gasMeter' param to 'BeginTransaction' call

Impact: caused 'make install' to fail on branch 'master' with the
following error:

cmd/gno/lint.go:147:34: not enough arguments in call to
ts.BeginTransaction
        have ("github.com/gnolang/gno/tm2/pkg/store/types".Store,
              "github.com/gnolang/gno/tm2/pkg/store/types".Store)
        want ("github.com/gnolang/gno/tm2/pkg/store/types".Store,
              "github.com/gnolang/gno/tm2/pkg/store/types".Store,
              "github.com/gnolang/gno/tm2/pkg/store/types".GasMeter)
    make[1]: *** [install] Error 1

Testing: This fix resolves test failure commanded by `make test`:

    FAIL	github.com/gnolang/gno/gnovm/cmd/gno [build failed]