fix(gotypecheck): refine `permCache` logic for stdlib packages (#4751)
### Description

This PR refines the permission cache logic for stdlib packages in the
type checker.

#### Problem

Previously, when running tests or linting on stdlib packages,
type-checking could fail with errors like:

```
math/bits/bits_test.gno:79:25: undefined: bits.DeBruijn64 (code=gnoTypeCheckError)
math/bits/bits_test.gno:1024:25: undefined: bits.OverflowError (code=gnoTypeCheckError)
...
```

This was caused by incorrectly caching stdlib packages even when
importing from other stdlibs

#### Solution

Now, stdlib packages are only cached in the permanent cache when
imported from non-stdlib packages.
This prevents stale or incomplete stdlib state from being reused during
stdlib tests, ensuring correct type-checking.